"""
Media parser — audio / video → Markdown transcript.

Strategy (priority order — subtitle-first guarantees maximum precision):

  1. **Subtitle file exists** (same stem, .srt / .vtt / .ass / .ssa):
     Parse the subtitle → Markdown with timestamps. Zero API cost, 100%
     accurate (subtitles are human-edited or platform-generated by Google
     / Bilibili / NicoNico's own high-quality ASR).

  2. **No subtitle → ASR** via `models.audio_transcription` config:
     DashScope Qwen3-ASR / OpenAI Whisper / any litellm-compatible engine.
     Configurable primary + fallback chain, same as Vision models.

  3. **Video files** (.mp4 / .mkv / ...): extract audio track with ffmpeg
     first, then apply 1→2 above on the extracted .wav.

Video frame understanding (画面理解):
  The strategy above only "listens" — the picture (slides, charts, whiteboard)
  is lost. When ``parsing.audio.video_frames.enabled`` is on (default), we ALSO
  sample frames with ffmpeg and attach them as ``ParseResult.pages`` so the
  pipeline's existing per-page Vision step (Phase 1.5) describes each frame —
  the very same path PDF/PPT page images take. A frame is just an image, so no
  new model interface is introduced and any Vision provider works. To keep the
  visual descriptions aligned with the spoken timeline, a ``<!-- pagebreak -->``
  is inserted into the transcript at each frame's timestamp; Vision then injects
  each frame's description into the matching time section (Mode A alignment),
  giving interleaved picture + speech instead of a wall of descriptions at the
  end. Frame count is capped by ``video_frames.max_frames`` (or, when null, the
  global ``parsing.vision.max_pages``) so a video costs no more Vision than a
  text document of equivalent page count.

Output: `ParseResult(markdown=..., metadata={...})` — plugs directly into
the existing pipeline (frontmatter → chunks → index → knowledge_map).

Metadata emitted:
  * format (mp3 / wav / mp4 / ...)
  * duration (seconds, via ffprobe)
  * language (from ASR or subtitle)
  * transcription_source ("subtitle" / "asr")
  * transcription_engine (e.g. "dashscope/qwen3-asr-flash-filetrans")

Config (all under parsing.audio):
  formats           — audio extensions to accept
  video_formats     — video extensions to accept (audio extracted via ffmpeg)
  prefer_subtitles  — look for .srt/.vtt before calling ASR (default true)
  language          — language hint for ASR ("auto" = detect)
  context           — hotwords / domain vocabulary for ASR
  include_timestamps— emit [MM:SS] markers in Markdown (default true)
  max_segment_seconds — long audio splitting threshold (default 600)
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
from io import BytesIO
from pathlib import Path
from typing import Any

from .base import BaseParser, PageData, ParseResult
from ..config import get_nested

logger = logging.getLogger(__name__)

# Default extension sets (overridable via config)
_DEFAULT_AUDIO_FORMATS = {
    "mp3", "wav", "m4a", "flac", "aac", "ogg", "wma", "opus",
}
_DEFAULT_VIDEO_FORMATS = {
    "mp4", "avi", "mkv", "webm", "mov", "wmv", "flv", "ts", "m4v",
}
_SUBTITLE_EXTENSIONS = [".srt", ".vtt", ".ass", ".ssa"]


class MediaParser(BaseParser):
    """
    Parser for audio and video files.

    Subtitle-first strategy ensures maximum precision; ASR is the fallback
    when no subtitle file is available.
    """

    def __init__(self, config: dict[str, Any]) -> None:
        super().__init__(config)
        audio_cfg = get_nested(config, "parsing.audio", {})
        self._audio_formats = set(audio_cfg.get("formats", _DEFAULT_AUDIO_FORMATS))
        self._video_formats = set(audio_cfg.get("video_formats", _DEFAULT_VIDEO_FORMATS))
        self._all_formats = self._audio_formats | self._video_formats

    def accepts(self, file_path: Path) -> bool:
        """True if the file extension matches a known audio/video format."""
        ext = file_path.suffix.lstrip(".").lower()
        return ext in self._all_formats

    def parse(
        self,
        file_path: Path,
        *,
        override_stream: BytesIO | None = None,
    ) -> ParseResult:
        """
        Parse an audio/video file into a Markdown transcript.

        override_stream is accepted for BaseParser interface compat but
        ignored — media files must be real files on disk (ffmpeg / ASR
        APIs need file paths, not streams).
        """
        _ = override_stream

        ext = file_path.suffix.lstrip(".").lower()
        is_video = ext in self._video_formats

        try:
            # Step 1: For video files, extract audio track
            audio_path = file_path
            if is_video:
                extracted = self._extract_audio(file_path)
                if extracted:
                    audio_path = extracted
                # If extraction fails, try ASR on the video file directly
                # (some ASR APIs accept video files)

            # Step 2: Transcribe the audio track — subtitle-first, ASR fallback.
            prefer_subs = get_nested(self.config, "parsing.audio.prefer_subtitles", True)
            subtitle_path = self._find_subtitle(file_path) if prefer_subs else None
            if subtitle_path:
                result = self._parse_from_subtitle(file_path, subtitle_path)
            else:
                result = self._parse_from_asr(file_path, audio_path)

            # Step 3: Video frame understanding (画面理解). The transcript only
            # carries speech; sample frames so the existing per-page Vision step
            # (pipeline Phase 1.5) describes the picture too. Audio-only files
            # and failed transcripts skip this entirely. Best-effort: any frame
            # failure leaves the transcript untouched (never raises).
            if is_video and result.success:
                self._attach_video_frames(file_path, result)

            return result

        except Exception as e:
            logger.error(f"Media parse failed for {file_path.name}: {e}")
            return ParseResult(
                markdown="",
                success=False,
                error=f"Media parse failed: {e}",
            )

    def supported_extensions(self) -> set[str]:
        return {f".{fmt}" for fmt in self._all_formats}

    # ------------------------------------------------------------------
    # Subtitle discovery
    # ------------------------------------------------------------------

    def _find_subtitle(self, file_path: Path) -> Path | None:
        """
        Look for a subtitle file with the same stem as the media file.

        Checks multiple extensions (.srt, .vtt, .ass, .ssa) and also
        language-tagged variants (e.g. video.ja.srt, video.en.vtt).
        Returns the first match.
        """
        stem = file_path.stem
        parent = file_path.parent

        for ext in _SUBTITLE_EXTENSIONS:
            # Exact match: video.srt
            candidate = parent / f"{stem}{ext}"
            if candidate.exists():
                return candidate

            # Language-tagged: video.ja.srt, video.en.srt, ...
            # yt-dlp produces these
            for tagged in parent.glob(f"{stem}.*{ext}"):
                if tagged.exists():
                    return tagged

        return None

    # ------------------------------------------------------------------
    # Subtitle → Markdown
    # ------------------------------------------------------------------

    def _parse_from_subtitle(
        self,
        original_path: Path,
        subtitle_path: Path,
    ) -> ParseResult:
        """Parse a subtitle file into timestamped Markdown."""
        include_ts = get_nested(self.config, "parsing.audio.include_timestamps", True)

        try:
            raw = subtitle_path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            # Try common Japanese encodings
            for enc in ("utf-8-sig", "cp932", "shift_jis"):
                try:
                    raw = subtitle_path.read_text(encoding=enc)
                    break
                except Exception:
                    continue
            else:
                return ParseResult(
                    markdown="", success=False,
                    error=f"Cannot read subtitle: {subtitle_path.name}",
                )

        ext = subtitle_path.suffix.lower()
        if ext == ".srt":
            lines = self._parse_srt(raw, include_timestamps=include_ts)
        elif ext == ".vtt":
            lines = self._parse_vtt(raw, include_timestamps=include_ts)
        else:
            # .ass / .ssa — strip formatting tags and use as plain text
            lines = self._parse_ass(raw, include_timestamps=include_ts)

        # Detect subtitle language from filename (video.ja.srt → "ja")
        lang = self._detect_subtitle_language(subtitle_path)

        metadata: dict[str, Any] = {
            "format": original_path.suffix.lstrip(".").lower(),
            "title": original_path.stem,
            "transcription_source": "subtitle",
            "subtitle_file": subtitle_path.name,
        }
        if lang:
            metadata["language"] = lang

        # Add duration if possible
        duration = self._get_duration(original_path)
        if duration:
            metadata["duration"] = duration

        markdown = "## Transcript\n\n" + "\n\n".join(lines)
        return ParseResult(markdown=markdown, metadata=metadata, success=True)

    @staticmethod
    def _parse_srt(raw: str, include_timestamps: bool) -> list[str]:
        """Parse SRT subtitle format into text lines."""
        blocks = re.split(r"\n\s*\n", raw.strip())
        lines: list[str] = []
        for block in blocks:
            block_lines = block.strip().split("\n")
            if len(block_lines) < 2:
                continue
            # SRT format: index, timestamp, text (1+ lines)
            # Skip index line, parse timestamp, collect text
            ts_match = re.match(
                r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->",
                block_lines[1] if len(block_lines) > 1 else "",
            )
            text_lines = block_lines[2:] if len(block_lines) > 2 else block_lines[1:]
            text = " ".join(line.strip() for line in text_lines if line.strip())
            # Strip HTML tags (some SRTs have <i>, <b>, etc.)
            text = re.sub(r"<[^>]+>", "", text)
            if not text:
                continue

            if include_timestamps and ts_match:
                h, m, s = int(ts_match.group(1)), int(ts_match.group(2)), int(ts_match.group(3))
                total_sec = h * 3600 + m * 60 + s
                mm, ss = divmod(total_sec, 60)
                lines.append(f"[{mm:02d}:{ss:02d}] {text}")
            else:
                lines.append(text)
        return lines

    @staticmethod
    def _parse_vtt(raw: str, include_timestamps: bool) -> list[str]:
        """Parse WebVTT subtitle format. Very similar to SRT."""
        # Strip WEBVTT header
        raw = re.sub(r"^WEBVTT\s*\n", "", raw.strip())
        # Strip NOTE blocks
        raw = re.sub(r"NOTE\s*\n.*?\n\n", "", raw, flags=re.DOTALL)
        # Reuse SRT parser (format is nearly identical after header strip)
        return MediaParser._parse_srt(raw, include_timestamps)

    @staticmethod
    def _parse_ass(raw: str, include_timestamps: bool) -> list[str]:
        """Parse ASS/SSA subtitle format (stripped of formatting)."""
        lines: list[str] = []
        for line in raw.split("\n"):
            if not line.startswith("Dialogue:"):
                continue
            # Dialogue: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
            parts = line.split(",", 9)
            if len(parts) < 10:
                continue
            text = parts[9].strip()
            # Strip ASS formatting tags {\xxx}
            text = re.sub(r"\{\\[^}]*\}", "", text)
            # Replace \N with space
            text = text.replace("\\N", " ").strip()
            if not text:
                continue

            if include_timestamps:
                start = parts[1].strip()
                # ASS timestamps: H:MM:SS.CC
                ts_match = re.match(r"(\d+):(\d{2}):(\d{2})", start)
                if ts_match:
                    h, m, s = int(ts_match.group(1)), int(ts_match.group(2)), int(ts_match.group(3))
                    total_sec = h * 3600 + m * 60 + s
                    mm, ss = divmod(total_sec, 60)
                    lines.append(f"[{mm:02d}:{ss:02d}] {text}")
                else:
                    lines.append(text)
            else:
                lines.append(text)
        return lines

    @staticmethod
    def _detect_subtitle_language(subtitle_path: Path) -> str:
        """
        Detect language from subtitle filename. yt-dlp produces names like:
          video.ja.srt, video.en.vtt, video.zh-Hans.srt
        """
        stem = subtitle_path.stem  # e.g. "video.ja"
        parts = stem.rsplit(".", 1)
        if len(parts) == 2:
            lang = parts[1]
            # Validate it looks like a language code
            if 2 <= len(lang) <= 10 and lang.replace("-", "").isalpha():
                return lang
        return ""

    # ------------------------------------------------------------------
    # ASR transcription
    # ------------------------------------------------------------------

    def _split_audio(self, audio_path: Path) -> list[tuple[Path, float]]:
        """
        Split long audio into segments for per-segment ASR.

        Returns a list of (segment_path, start_time_seconds). If the audio
        is shorter than max_segment_seconds, returns [(original, 0.0)].

        Aligned with qwen_asr.py's split_audio logic: fixed-duration
        segments via ffmpeg -ss/-t, output as mp3 to keep file sizes small.
        """
        from ..utils.binary_finder import find_binary
        max_seg = int(get_nested(
            self.config, "parsing.audio.max_segment_seconds", 150
        ))

        # Get total duration
        duration_str = self._get_duration(audio_path)
        if not duration_str:
            return [(audio_path, 0.0)]  # can't detect → send as-is

        # Parse duration string (MM:SS or H:MM:SS) back to seconds
        parts = duration_str.split(":")
        try:
            if len(parts) == 3:
                total_sec = int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
            elif len(parts) == 2:
                total_sec = int(parts[0]) * 60 + int(parts[1])
            else:
                total_sec = int(parts[0])
        except ValueError:
            return [(audio_path, 0.0)]

        if total_sec <= max_seg:
            return [(audio_path, 0.0)]

        ffmpeg = find_binary("ffmpeg", self.config)
        if not ffmpeg:
            logger.warning(
                f"Audio {audio_path.name} is {total_sec}s but ffmpeg not available "
                f"to split. Sending whole file (may exceed API limits)."
            )
            return [(audio_path, 0.0)]

        # Split into segments
        segments: list[tuple[Path, float]] = []
        seg_dir = audio_path.parent
        start = 0.0
        idx = 0
        while start < total_sec:
            seg_path = seg_dir / f"{audio_path.stem}_seg{idx:03d}.mp3"
            try:
                subprocess.run(
                    [ffmpeg, "-y", "-i", str(audio_path),
                     "-ss", str(start), "-t", str(max_seg),
                     "-acodec", "libmp3lame", "-ar", "16000", "-ac", "1",
                     str(seg_path)],
                    capture_output=True, timeout=120,
                )
                if seg_path.exists() and seg_path.stat().st_size > 0:
                    segments.append((seg_path, start))
            except Exception as e:
                logger.debug(f"Segment {idx} split failed: {e}")
            start += max_seg
            idx += 1

        if segments:
            logger.info(
                f"Split {audio_path.name} ({total_sec}s) → "
                f"{len(segments)} segments of ≤{max_seg}s"
            )
            return segments

        # Splitting failed entirely → return original
        return [(audio_path, 0.0)]

    def _parse_from_asr(
        self,
        original_path: Path,
        audio_path: Path,
    ) -> ParseResult:
        """
        Transcribe via configured ASR engine with automatic segmentation.

        For long audio, splits into segments (via ffmpeg), transcribes each
        in parallel, and merges results with time offsets. Aligned with
        qwen_asr.py's transcribe_qwen() architecture.
        """
        from ..models.audio_provider import transcribe_audio
        from ..models.cache import AICache, content_hash_file
        from concurrent.futures import ThreadPoolExecutor, as_completed

        model_config = get_nested(self.config, "models.audio_transcription", {})
        language = get_nested(self.config, "parsing.audio.language", None)
        if language == "auto":
            language = None
        hotwords = get_nested(self.config, "parsing.audio.context", None)
        include_ts = get_nested(self.config, "parsing.audio.include_timestamps", True)

        # Cache setup (caches the FINAL merged result by original file hash)
        cache_enabled = get_nested(self.config, "cache.enabled", True)
        cache_dir = get_nested(self.config, "cache.dir", ".docingest_cache")
        cache = AICache(cache_dir=cache_dir, enabled=cache_enabled)

        try:
            primary = model_config.get("primary", {})
            model_name = f"{primary.get('provider', 'dashscope')}/{primary.get('model', 'qwen3-asr-flash')}"
            audio_hash = content_hash_file(audio_path)

            def _do_transcribe() -> str:
                """
                Split → parallel ASR → merge. Aligned with qwen_asr.py.

                Returns serialised JSON for cache storage.
                """
                segments_data = self._split_audio(audio_path)
                parallel = get_nested(self.config, "performance.parallel_files", 4)

                if len(segments_data) == 1:
                    # Short audio — single call, no parallelism needed
                    seg_path, start_sec = segments_data[0]
                    result = transcribe_audio(
                        audio_path=seg_path,
                        model_config=model_config,
                        language=language,
                        hotwords=hotwords,
                    )
                    return json.dumps({
                        "text": result.text,
                        "language": result.language,
                        "engine": result.engine,
                        "segments": [{"start": start_sec, "end": 0, "text": result.text}],
                    }, ensure_ascii=False)

                # Long audio — parallel transcription per segment
                logger.info(
                    f"ASR: {len(segments_data)} segments, "
                    f"parallel={parallel}"
                )
                results: list[dict | None] = [None] * len(segments_data)

                def _transcribe_segment(idx: int, seg_path: Path) -> tuple[int, dict]:
                    r = transcribe_audio(
                        audio_path=seg_path,
                        model_config=model_config,
                        language=language,
                        hotwords=hotwords,
                    )
                    return idx, {"text": r.text, "language": r.language, "engine": r.engine}

                with ThreadPoolExecutor(max_workers=parallel) as pool:
                    futures = {
                        pool.submit(_transcribe_segment, i, seg_path): i
                        for i, (seg_path, _) in enumerate(segments_data)
                    }
                    for future in as_completed(futures):
                        try:
                            idx, seg_result = future.result()
                            results[idx] = seg_result
                            logger.debug(f"  segment {idx + 1}/{len(segments_data)} done")
                        except Exception as e:
                            idx = futures[future]
                            logger.warning(f"  segment {idx + 1} failed: {e}")
                            results[idx] = {"text": "", "language": "", "engine": ""}

                # Merge results in order
                merged_texts = []
                merged_segments = []
                detected_lang = ""
                engine = ""
                for i, r in enumerate(results):
                    if r and r.get("text"):
                        merged_texts.append(r["text"])
                        start_sec = segments_data[i][1]
                        merged_segments.append({
                            "start": start_sec,
                            "end": start_sec + get_nested(self.config, "parsing.audio.max_segment_seconds", 150),
                            "text": r["text"],
                        })
                        if not detected_lang and r.get("language"):
                            detected_lang = r["language"]
                        if not engine and r.get("engine"):
                            engine = r["engine"]

                return json.dumps({
                    "text": "\n".join(merged_texts),
                    "language": detected_lang,
                    "engine": engine,
                    "segments": merged_segments,
                }, ensure_ascii=False)

            cached_json = cache.get_or_call(
                model_name=model_name,
                content_hash=audio_hash,
                call_fn=_do_transcribe,
                extra_key="audio_asr",
            )

            data = json.loads(cached_json)

        except Exception as e:
            return ParseResult(
                markdown="", success=False,
                error=f"ASR transcription failed: {e}",
            )
        finally:
            if cache_enabled:
                cache.close()

        # Build Markdown from ASR result
        md_lines: list[str] = []
        if data.get("segments"):
            for seg in data["segments"]:
                total_sec = int(seg["start"])
                mm, ss = divmod(total_sec, 60)
                if include_ts:
                    md_lines.append(f"[{mm:02d}:{ss:02d}] {seg['text']}")
                else:
                    md_lines.append(seg["text"])
        else:
            md_lines.append(data.get("text", ""))

        metadata: dict[str, Any] = {
            "format": original_path.suffix.lstrip(".").lower(),
            "title": original_path.stem,
            "transcription_source": "asr",
            "transcription_engine": data.get("engine", ""),
        }
        if data.get("language"):
            metadata["language"] = data["language"]

        duration = self._get_duration(original_path)
        if duration:
            metadata["duration"] = duration

        # Also check for info.json from yt-dlp (title/uploader/description)
        info = self._load_info_json(original_path)
        if info:
            if info.get("title"):
                metadata["title"] = info["title"]
            if info.get("uploader"):
                metadata["uploader"] = info["uploader"]
            if info.get("description"):
                metadata["description"] = info["description"][:500]

        markdown = "## Transcript\n\n" + "\n\n".join(md_lines)

        # Prepend video info if available
        if info:
            header_parts = []
            if info.get("title"):
                header_parts.append(f"# {info['title']}")
            if info.get("uploader"):
                header_parts.append(f"**Uploader:** {info['uploader']}")
            if info.get("description"):
                desc = info["description"][:500]
                header_parts.append(f"\n> {desc}")
            if header_parts:
                markdown = "\n\n".join(header_parts) + "\n\n" + markdown

        return ParseResult(markdown=markdown, metadata=metadata, success=True)

    # ------------------------------------------------------------------
    # Video frame understanding (画面理解)
    # ------------------------------------------------------------------

    def _attach_video_frames(self, video_path: Path, result: ParseResult) -> None:
        """Sample frames and attach them for Vision enrichment (in place).

        Fills result.pages (one PageData per frame → pipeline Phase 1.5 Vision
        describes each) and splices a pagebreak into the transcript at each
        frame's timestamp so Vision aligns the description to the matching time
        section (Mode A), interleaving picture with speech. Best-effort: config
        off / no ffmpeg / zero frames leave result untouched. Never raises."""
        cfg = get_nested(self.config, "parsing.audio.video_frames", {}) or {}
        if not cfg.get("enabled", True):
            return
        frames = self._extract_frames(video_path)
        if not frames:
            return
        # num_pictures=1 keeps triage from skipping a frame as "text-only";
        # text="" lets the full-page Vision prompt describe the whole frame.
        result.pages = [
            PageData(page_no=i + 1, text="", image_path=str(fp), num_pictures=1)
            for i, (fp, _ts) in enumerate(frames)
        ]
        result.markdown = self._splice_frame_pagebreaks(
            result.markdown, [ts for _fp, ts in frames]
        )
        result.metadata["has_video_frames"] = True
        result.metadata["frames_extracted"] = len(frames)

    def _extract_frames(self, video_path: Path) -> list[tuple[Path, float]]:
        """Sample frames every interval_sec via ffmpeg, capped by max_frames
        (null → inherit parsing.vision.max_pages). Returns [(path, ts_sec), ...]
        in time order, or [] when ffmpeg/duration unavailable. Frames written as
        <stem>_frame####.jpg next to the video and reused on re-run."""
        from ..utils.binary_finder import find_binary

        cfg = get_nested(self.config, "parsing.audio.video_frames", {}) or {}
        interval = float(cfg.get("interval_sec", 10) or 10)
        if interval <= 0:
            interval = 10.0
        max_frames = cfg.get("max_frames")
        if max_frames is None:
            max_frames = get_nested(self.config, "parsing.vision.max_pages", 50)
        max_frames = int(max_frames) if max_frames is not None else None

        total_sec = self._duration_seconds(video_path)
        if not total_sec:
            logger.debug(f"Cannot read duration of {video_path.name}; skip frames")
            return []
        ffmpeg = find_binary("ffmpeg", self.config)
        if not ffmpeg:
            logger.debug("ffmpeg not found; cannot sample video frames")
            return []

        # interval/2 first (mid-interval avoids a black/title frame at t=0).
        timestamps: list[float] = []
        t = interval / 2.0
        while t < total_sec:
            timestamps.append(round(t, 2))
            t += interval
        if max_frames is not None and len(timestamps) > max_frames:
            logger.info(
                f"Video {video_path.name}: {len(timestamps)} frames at "
                f"{interval}s exceeds cap {max_frames} — resampling evenly."
            )
            # Resample evenly across the whole duration (not just the head).
            step = total_sec / max_frames
            timestamps = [round(step * (i + 0.5), 2) for i in range(max_frames)]

        frames: list[tuple[Path, float]] = []
        for idx, ts in enumerate(timestamps):
            out_path = video_path.with_name(f"{video_path.stem}_frame{idx:04d}.jpg")
            if out_path.exists() and out_path.stat().st_size > 0:
                frames.append((out_path, ts))
                continue
            try:
                subprocess.run(
                    [ffmpeg, "-y", "-ss", str(ts), "-i", str(video_path),
                     "-frames:v", "1", "-q:v", "3", str(out_path)],
                    capture_output=True, timeout=60,
                )
                if out_path.exists() and out_path.stat().st_size > 0:
                    frames.append((out_path, ts))
            except Exception as e:
                logger.debug(f"Frame extraction at {ts}s failed: {e}")

        if frames:
            logger.info(
                f"Sampled {len(frames)} frame(s) from {video_path.name} "
                f"(every {interval}s, {total_sec:.0f}s total)"
            )
        return frames

    @staticmethod
    def _splice_frame_pagebreaks(markdown: str, frame_times: list[float]) -> str:
        """Insert one PAGEBREAK_MARKER per frame at its timestamp position so
        per-frame Vision results align to the matching transcript time section.
        Emits exactly len(frame_times) markers, in order. Lines without a
        leading [MM:SS]/[H:MM:SS] timestamp pass through untouched."""
        from .base import PAGEBREAK_MARKER

        if not frame_times:
            return markdown

        ts_re = re.compile(r"^\[(\d{1,2}):(\d{2})(?::(\d{2}))?\]")

        def line_time(line: str) -> float | None:
            m = ts_re.match(line.strip())
            if not m:
                return None
            parts = [int(x) for x in m.groups() if x is not None]
            if len(parts) == 3:
                return parts[0] * 3600 + parts[1] * 60 + parts[2]
            return parts[0] * 60 + parts[1]

        out: list[str] = []
        frame_idx = 0
        n_frames = len(frame_times)
        for line in markdown.split("\n"):
            lt = line_time(line)
            if lt is not None:
                while frame_idx < n_frames and frame_times[frame_idx] <= lt:
                    out.append(PAGEBREAK_MARKER)
                    frame_idx += 1
            out.append(line)
        # Frames past the last timestamp: append remaining markers at the end so
        # every frame still gets a section.
        while frame_idx < n_frames:
            out.append(PAGEBREAK_MARKER)
            frame_idx += 1
        return "\n".join(out)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_audio(self, video_path: Path) -> Path | None:
        """Extract audio track from video via ffmpeg."""
        from ..utils.binary_finder import find_binary

        ffmpeg = find_binary("ffmpeg", self.config)
        if not ffmpeg:
            logger.debug("ffmpeg not found; cannot extract audio from video")
            return None

        out_path = video_path.with_suffix(".wav")
        if out_path.exists() and out_path.stat().st_size > 0:
            return out_path  # already extracted

        try:
            subprocess.run(
                [ffmpeg, "-i", str(video_path),
                 "-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1",
                 "-y", str(out_path)],
                capture_output=True, timeout=300,
            )
            if out_path.exists() and out_path.stat().st_size > 0:
                return out_path
        except Exception as e:
            logger.debug(f"ffmpeg audio extraction failed: {e}")

        return None

    def _get_duration(self, file_path: Path) -> str:
        """Get media duration as human-readable string via ffprobe."""
        from ..utils.binary_finder import find_binary

        ffprobe = find_binary("ffprobe", self.config)
        if not ffprobe:
            return ""

        try:
            result = subprocess.run(
                [ffprobe, "-v", "quiet",
                 "-show_entries", "format=duration",
                 "-of", "default=noprint_wrappers=1:nokey=1",
                 str(file_path)],
                capture_output=True, text=True, timeout=30,
            )
            seconds = float(result.stdout.strip())
            m, s = divmod(int(seconds), 60)
            h, m = divmod(m, 60)
            if h > 0:
                return f"{h}:{m:02d}:{s:02d}"
            return f"{m}:{s:02d}"
        except Exception:
            return ""

    def _duration_seconds(self, file_path: Path) -> float:
        """Media duration in seconds via ffprobe, or 0.0 if unavailable."""
        from ..utils.binary_finder import find_binary

        ffprobe = find_binary("ffprobe", self.config)
        if not ffprobe:
            return 0.0
        try:
            result = subprocess.run(
                [ffprobe, "-v", "quiet",
                 "-show_entries", "format=duration",
                 "-of", "default=noprint_wrappers=1:nokey=1",
                 str(file_path)],
                capture_output=True, text=True, timeout=30,
            )
            return float(result.stdout.strip())
        except Exception:
            return 0.0

    @staticmethod
    def _load_info_json(file_path: Path) -> dict[str, Any] | None:
        """Load yt-dlp's .info.json if it exists alongside the media file."""
        info_path = file_path.with_suffix(".info.json")
        if not info_path.exists():
            # Also try with the video ID pattern: <id>.info.json
            for candidate in file_path.parent.glob("*.info.json"):
                info_path = candidate
                break
            else:
                return None

        try:
            with open(info_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return None
